spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
    include: oauth, db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379


server:
  port: 8084

logging:
  level:
    org:
      springframework: debug
